services:
  frontend:
    image: busybrainx99/test-app:v3
    ports:
      - '5173:5173' # assuming frontend is on port 5173
    env_file:
      - .env.frontend
    environment:
      - VITE_HOST=0.0.0.0
    depends_on:
      - backend

  backend:
    image: busybrainx99/test-app-backend:v2
    ports:
      - '8000:8000' # assuming backend is on port 8000
    env_file:
      - .env.backend
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: changethis123
      POSTGRES_DB: app
    ports:
      - '5432:5432'
# version: '3.8'

# services:
#   frontend:
#     build:
#       context: ./frontend
#       dockerfile: Dockerfile
#     ports:
#       - "5173:5173"
#     depends_on:
#       - backend
#     environment:
#       # Replace with actual API URL for local testing
#       REACT_APP_API_URL: "http://backend:8000"

#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db
#     environment:
#       # Set environment variables for DB connection
#       DATABASE_URL: "postgresql://user:password@db:5432/mydatabase"

#   db:
#     image: postgres:15
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: mydatabase
#     volumes:
#       - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata:
